spring:
  application:
    name: users
  config:
    import: ${IMPORT_LOCATION}
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: ${SECRET_USER}
    password: ${SECRET_PASSWORD}

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8100