spring:
  application:
    name: products
  config:
    import: ${IMPORT_LOCATION}
  r2dbc:
    name: db
    url: r2dbc:h2:mem:///productsdb
    username: ${SECRET_USER}
    password: ${SECRET_PASSWORD}

server:
  port: 8200

logging:
  level:
    org:
      springframework:
        r2dbc: debug 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/