spring:
  application:
    name: gateway
  config:
    import: ${IMPORT_LOCATION}
  cloud:
    gateway:
      default-filters:
      - name: CustomGatewayFilter
      routes:
      - id:
        predicates:
        - Path=/users/**
        uri: lb://users/users/**
      
      - id:
        predicates:
        - Path=/products/**
        uri: lb://products/products/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/